apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgAPuKZnRY4uwGZoXZTkgwXmIxFZsUW9xwUI67zcn+A3kT3HgtI/FH7bfe6wDozOAniy3j9VdkH4ElqOjP0/CI6e4jwAlR992P8AawF896JEnZN628hvM6fcZBDdgSUbbbl/0rMbk2S6Ba23I4/l8i6weiE1ABEj/MoTclUZpuZkY9Oyl4SlkmombxxgfvUFBpQCc1C0MA5tPNfvdARYNtpw8Bjo8qOq9ZcDGBtishhjCMyqIN/fubFQXEX8dRbEex8UlapJL/qXpfTEJa4qBA+k5Bor70gsvnckyu4t/rQ0b3Rbpc4B12R0FKBU9ZNWd1CLIKqJppj1uVSpt70PGV7Qf0HeWAS0ITWJ+gQw3uC+Uj017BI3FDsaIBzkc7+BJyNXa4lLmqNdkcoXULgx+XFR8DbX/GX9x2WrpGkFH32GZfAqCsuQeZVD0eCi/wGomoZdmEcdpApk2H3OrqcM5WMHbHdNL08NWCCbPvhBhU0z3uQU/nZWdkGUQVSxMgnwfVLJbMwL+CPXbf55CMIbxMch6/TiWUL4h0MVuCBbgPNkfXcFhkj+KEe7v7rpxemM1QMnVDx+X8Av5Abt7dJqZSxtfpsgKqYhuQNT5D5AUapZ/gU1RSntZ9jA8fUmG8UpMwIUN2W7LHFW9F08QwVyFAN7HHUWteDBGLgiz8Ta1QlYN0yqSQXxJfPf/mhBCeTGlruoqm+YGdVbcA==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

